# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-04 17:09
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('previa', '0002_noticia_puntuacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puntuacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='puntuacion',
        ),
        migrations.RemoveField(
            model_name='puntaje',
            name='puntuacion',
        ),
        migrations.AddField(
            model_name='puntaje',
            name='noticia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='previa.Noticia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='puntaje',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='puntuacion',
            name='puntaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntuaciones', to='previa.Puntaje'),
        ),
    ]
