# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-04 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('previa', '0003_auto_20180704_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
