# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-04 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('previa', '0004_noticia_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='image',
            field=models.ImageField(default=1, upload_to=b''),
            preserve_default=False,
        ),
    ]
